#
# Executes commands at logout.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code only if STDERR is bound to a TTY.
[[ -o INTERACTIVE && -t 2 ]] && {

# To print a message on logout:
# uncomment all of the commented-out lines below, and
# insert your content at <your message here>

# cat <<-EOF
#
# <your message here>
#
# EOF
#
# } >&2
