#
# Executes commands at logout.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code only if STDERR is bound to a TTY.
[[ -o INTERACTIVE && -t 2 ]] && {

# To print a message on logout:
# uncomment the commented-out lines below, an
# insert your content below the cat:

# cat <<-EOF
#
# add your message here
#
# EOF
#
# } >&2
