#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ -z "$BROWSER" && "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/{,s}bin(N)
  /opt/{homebrew,local}/{,s}bin(N)
  /usr/local/{,s}bin(N)
  $path
)

#
# Editors
#

if [[ -z "$EDITOR" ]]; then
  export EDITOR=$(whence vim nano vi | head -n 1)
fi
if [[ -z "$VISUAL" ]]; then
  export VISUAL=$EDITOR
fi
if [[ -z "$PAGER" ]]; then
  export PAGER='less'
fi

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X to enable it.
if [[ -z "$LESS" ]]; then
  export LESS='-g -i -M -R -S -w -X -z-4'
fi

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if [[ -z "$LESSOPEN" ]] && (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )


#
# Time Zone
#

export TZ=America/Los_Angeles

#
# Fancy Colors
#

# Set variables that will be read by darken/brighten
# export BRIGHT_BAT='Solarized (light)'
# export BRIGHT_PROMPT='statusline -l'
# export BRIGHT_TERM='Solarized Light'
#
# export DARK_BAT='Solarized (dark)'
# export DARK_PROMPT='statusline -d'
# export DARK_TERM='Solarized Dark'

# Disable Eternal Terminal telemtry
# MisterTea/EternalTerminal/src/terminal/TelemetryService.cpp
export ET_NO_TELEMETRY=true

# awx things that change more often
# export TOWER_FORMAT=human
# export TOWER_HOST="https://awx"
# export TOWER_VERIFY_SSL=false
# export TOWER_USERNAME=$USER
