#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Treat top-level shells as "login" shells.
if [[ $SHLVL == 1 && ! -o LOGIN ]]; then
    source "${ZDOTDIR:-$HOME}/.zprofile"
fi

