# Sourced on all invocations of shell unless -f option is set
# Command Search Path
# Important Environment Variables
# Do not produce output
# Do not assume tty
#
# $ZDOTDIR/.zshenv
# $ZDOTDIR/.zprofile
# $ZDOTDIR/.zshrc
# $ZDOTDIR/.zlogin

export LANG=en_US.UTF-8

# Setup path
path=(
    $HOME/Library/Scripts/bin/`/usr/bin/uname -s`/`/usr/bin/uname -m`
    $HOME/Library/Scripts/bin/`/usr/bin/uname -s`
    $HOME/Library/Scripts/bin/
    $HOME/Library/Python/bin
    /opt/local/bin  /usr/local/bin  /usr/bin  /bin
    /opt/local/sbin /usr/local/sbin /usr/sbin /sbin
    /usr/X11R6/bin
    /opt/local/Library/Frameworks/Python.framework/Versions/Current/bin
)

if [ -d $HOME/.rvm/bin ]; then
    path=($path $HOME/.rvm/bin)
fi

# Go
if [ -d /usr/local/go/bin ]; then
    path=($path /usr/local/go/bin)
    declare -x GOPATH="/Users/lanhel/Developer/SpaceMonkey/katamari/go"
fi


# Setup MANPATH
manpath=(
    $HOME/man
    /opt/local/man
    /usr/local/share/man
    /usr/local/man
    /usr/share/man
    /usr/man
)

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )
# Setup file creation mask
#umask 077

# Setup by operating system type
case `/usr/bin/uname -s` in
    Darwin)
	path=($path /System/Applications /Applications)

	declare -x MANPATH=`echo $MANPATH | sed 's*'$HOME/man'*'$HOME/Library/man'*g'`
	;;

    linux*)
    ;;
esac

# Setup by processor type
case `/usr/bin/uname -m` in
    powerpc)
    ;;

    i386)
    ;;
esac

# Setup by host name
case `/usr/bin/uname -n` in
    helsten)
    ;;

    pfiefferhorn)
    ;;
esac

# Setup by subsystem
for f in `find $HOME/Library/Scripts/config -name '*.shenv' -print`; do
    source "$f"
done

# Ensure path arrays do not contain duplicates
typeset -gU cdpath fpath mailpath path


