#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source ~/.profile
export PATH="$JAVA_HOME/bin:$PATH"
[[ /usr/local/bin/kubectl ]] && source <(kubectl completion zsh)
source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
DEFAULT_USER=yousihan
prompt_context() {
  if [[ "$USER" == "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
    emojis=("⚡️" "🔥" "💀" "👑" "😎" "🐸" "🐵" "🦄" "🌈" "🍻" "🚀" "💡" "🎉" "🔑" "🇹🇭" "🚦" "🌙")
    RAND_EMOJI_N=$(( $RANDOM % ${#emojis[@]} + 1))
    prompt_segment black default "${emojis[$RAND_EMOJI_N]} "
  fi
}

alias kprod="kubectl --context=us-east-1a -n amp-commerce-fraud-prod"
alias kdev="kubectl --context=us-west-1a -n amp-commerce-fraud-dev"
alias kplay="kubectl --context=us-west-1a -n amp-commerce-fraud-playground"

gup () {
  remote="$1"
  branch="$2"
  if [ -z $remote ]; then
    echo "err: set remote, gup {remote} {branch}"
    return 0
  fi
  if [ -z $branch ]; then
    echo "err: set branch, gup {remote} {branch}"
  fi
  git fetch "$remote"
  git rebase "$remote/$branch"
}
 
export PATH="$HOME/go/bin:$PATH"

MAVEN_OPTS="-Xms8G -Xmx24G -XX:+UseG1GC"
