#Load common configuration
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zprofile" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zprofile"
fi

#Source miniconda2
export PATH=$HOME/sw/miniconda2/bin:$HOME/sw/miniconda2/envs/py3/bin:$PATH

#Define some custom variables
export PROMOTION="$HOME/Dropbox/Studium/PROMOTION/"

#PyModules (my python modules)
export PYTHONPATH=$HOME/sw/PyModules

#SciFi40 Software
export PATH=$HOME/SciFi/lhcb-scifi40-software/bin:$PATH

# ROOT6 (binary download)
#source /Applications/root_v6.14.02/bin/thisroot.sh
source /Applications/root_v6.14.04/bin/thisroot.sh
