#Load common configuration
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zprofile" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zprofile"
fi

#Define some custom variables
export PROMOTION="$HOME/Dropbox/Studium/PROMOTION/"

#PyModules (my python modules)
export PYTHONPATH=$HOME/sw/PyModules

#SciFi40 Software
export PATH=$HOME/SciFi/lhcb-scifi40-software/bin:$PATH

# ROOT6 (binary download)
#source /Applications/root_v6.14.02/bin/thisroot.sh
source /Applications/root_v6.14.04/bin/thisroot.sh

# added by Miniconda3 4.5.12 installer
# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$(CONDA_REPORT_ERRORS=false '/miniconda3/bin/conda' shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    \eval "$__conda_setup"
else
    if [ -f "/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/miniconda3/etc/profile.d/conda.sh"
        CONDA_CHANGEPS1=false conda activate base
    else
        \export PATH="/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda init <<<
