#Load common configuration
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zshrc" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zshrc"
fi

#SSH automatically renews kerberos ticket to CERN.CH if needed
local _ssh=$(which ssh)  #Backup original ssh as _ssh
ssh()
{
    if ! (klist --test 2> /dev/null); then
        printf "Renewing kerberos credentials for dabernin@CERN.CH..."
        kinit dabernin@CERN.CH
        printf "done\n"
    fi

    TERM=xterm-256color ${_ssh} $@
}
