set-option -g default-shell $SHELL
set-window-option -g mode-keys vi
set-option -g prefix C-t
setw -g mouse on
unbind-key C-b
bind s split-window -v -c "#{pane_current_path}"
bind S select-layout even-vertical
bind v split-window -h -c "#{pane_current_path}"
bind V select-layout even-horizontal
bind n select-pane -L
bind e select-pane -D
bind o select-pane -U
bind i select-pane -R
bind w killp
bind z setw synchronize-panes
bind y copy
bind t new-window -c "#{pane_current_path}"

