.TH OSX
.PP
Defines Mac OS X
.UR http://www.apple.com/macosx/
.UE
aliases and functions.
.SH Aliases
.RS
.IP \(bu 2
\fB\fCcdf\fR changes the current working director to the current \fIFinder\fP
directory.
.IP \(bu 2
\fB\fCpushdf\fR pushes the current working directory onto the directory queue and
.IP \(bu 2
\fB\fCql\fR quick looks at files.
.IP \(bu 2
\fB\fCrm-osx-cruft\fR deletes .DS_Store, __MACOSX cruft.
.RE
.SH Functions
.RS
.IP \(bu 2
\fB\fCmanb\fR opens \fIman\fP pages in \fIBwana.app\fP
.UR http://bruji.com/bwana/
.UE .
.IP \(bu 2
\fB\fCmanp\fR opens \fIman\fP pages in \fIPreview.app\fP.
.IP \(bu 2
\fB\fCpfd\fR prints the current \fIFinder\fP directory.
.IP \(bu 2
\fB\fCpfs\fR prints the current \fIFinder\fP selection.
.IP \(bu 2
\fB\fCtab\fR creates a new tab (works in both \fITerminal\fP and \fIiTerm\fP
.UR http://www.iterm2.com/
.UE ).
.IP \(bu 2
\fB\fCtrash\fR moves files and folders to \fITrash\fP.
.RE
.SH Authors
.PP
\fIThe authors of this module should be contacted via the issue tracker
.UR https://github.com/sorin-ionescu/prezto/issues
.UE .\fP
.RS
.IP \(bu 2
Sorin Ionescu
.UR https://github.com/sorin-ionescu
.UE
.RE
