.TH Command\-Not\-Found
.PP
Loads the command\-not\-found
.UR https://code.launchpad.net/command-not-found
.UE
tool on Debian\-based distributions.
.SH Authors
.PP
\fIThe authors of this module should be contacted via the issue tracker
.UR https://github.com/sorin-ionescu/prezto/issues
.UE .\fP
.RS
.IP \(bu 2
Joseph Booker
.UR https://github.com/sargas
.UE
.RE
