.TH Yum
.PP
Defines yum
.UR http://yum.baseurl.org
.UE
aliases.
.SH Aliases
.RS
.IP \(bu 2
\fB\fCyumc\fR removes package(s) and leaves.
.IP \(bu 2
\fB\fCyumi\fR installs package(s).
.IP \(bu 2
\fB\fCyumh\fR displays history.
.IP \(bu 2
\fB\fCyuml\fR lists packages.
.IP \(bu 2
\fB\fCyumL\fR lists installed packages.
.IP \(bu 2
\fB\fCyumq\fR displays package information.
.IP \(bu 2
\fB\fCyumr\fR removes package(s).
.IP \(bu 2
\fB\fCyums\fR searches for a package.
.IP \(bu 2
\fB\fCyumu\fR updates packages.
.IP \(bu 2
\fB\fCyumU\fR upgrates packages.
.RE
.SH Authors
.PP
\fIThe authors of this module should be contacted via the issue tracker
.UR https://github.com/sorin-ionescu/prezto/issues
.UE .\fP
.RS
.IP \(bu 2
Sorin Ionescu
.UR https://github.com/sorin-ionescu
.UE
.RE
