.TH Environment
.PP
Sets general shell options and defines environment variables.
.PP
This module must be loaded first.
.SH Environment Variables
.SH Contributors
.PP
This module \fBMUST NOT\fP rely on any command not built in Zsh.
.PP
Non\-interactive environment variables should be defined in \fIzshenv\fP.
.SH Authors
.PP
\fIThe authors of this module should be contacted via the issue tracker
.UR https://github.com/sorin-ionescu/prezto/issues
.UE .\fP
.RS
.IP \(bu 2
Sorin Ionescu
.UR https://github.com/sorin-ionescu
.UE
.RE
