.TH Terminal
.PP
Sets terminal window and tab titles.
.SH Settings
.SS Auto\-Title
.PP
To auto set the terminal window and tab titles with the current command or
directory, add the following to \fIzpreztorc\fP:
.nf
zstyle ':prezto:module:terminal' auto-title 'yes'
.fi
.SH Authors
.PP
\fIThe authors of this module should be contacted via the issue tracker
.UR https://github.com/sorin-ionescu/prezto/issues
.UE .\fP
.RS
.IP \(bu 2
James Cox
.UR https://github.com/imajes
.UE
.IP \(bu 2
Sorin Ionescu
.UR https://github.com/sorin-ionescu
.UE
.RE
