.TH Rsync
.PP
Defines rsync
.UR http://rsync.samba.org
.UE
aliases.
.PP
Mac OS X users are encouraged to use Bombich's rsync
.UR http://www.bombich.com/rsync.html
.UE , which has HFS+
enhancements.
.SH Aliases
.RS
.IP \(bu 2
\fB\fCrsync-copy\fR copies files and directories from \fIsource\fP to \fIdestination\fP.
.IP \(bu 2
\fB\fCrsync-move\fR moves files and directories from \fIsource\fP to \fIdestination\fP.
.IP \(bu 2
\fB\fCrsync-update\fR updates files and directories on \fIdestination\fP.
.IP \(bu 2
\fB\fCrsync-synchronize\fR synchronizes files and directories between \fIsource\fP and
\fIdestination\fP.
.RE
.SH Authors
.PP
\fIThe authors of this module should be contacted via the issue tracker
.UR https://github.com/sorin-ionescu/prezto/issues
.UE .\fP
.RS
.IP \(bu 2
Sorin Ionescu
.UR https://github.com/sorin-ionescu
.UE
.RE
