.TH Ruby on Rails
.PP
Defines Ruby on Rails
.UR http://rubyonrails.org
.UE
aliases.
.SH Aliases
.RS
.IP \(bu 2
\fB\fCror\fR is short for \fB\fCrails\fR.
.IP \(bu 2
\fB\fCrorc\fR starts the Rails console.
.IP \(bu 2
\fB\fCrordc\fR starts the Rails console connected to the database.
.IP \(bu 2
\fB\fCrordm\fR migrates the database.
.IP \(bu 2
\fB\fCrordM\fR migrates the database and recreates the test database.
.IP \(bu 2
\fB\fCrordr\fR rolls the database schema back to the previous version.
.IP \(bu 2
\fB\fCrorg\fR generates new code.
.IP \(bu 2
\fB\fCrorl\fR displays the log.
.IP \(bu 2
\fB\fCrorlc\fR truncates logs to zero bytes.
.IP \(bu 2
\fB\fCrorp\fR installs a plugin.
.IP \(bu 2
\fB\fCrorr\fR runs code in the application environment.
.IP \(bu 2
\fB\fCrors\fR starts the Rails server.
.IP \(bu 2
\fB\fCrorsd\fR starts the Rails server with the debugger.
.IP \(bu 2
\fB\fCrorx\fR destroys newly generated code.
.RE
.SH Authors
.PP
\fIThe authors of this module should be contacted via the issue tracker
.UR https://github.com/sorin-ionescu/prezto/issues
.UE .\fP
.RS
.IP \(bu 2
Robby Russell
.UR https://github.com/robbyrussell
.UE
.IP \(bu 2
Jake Bell
.UR https://github.com/theunraveler
.UE
.IP \(bu 2
Sorin Ionescu
.UR https://github.com/sorin-ionescu
.UE
.RE
