.TH Macports
.PP
Defines MacPorts aliases and adds MacPorts directories to path variables.
.SH Aliases
.RS
.IP \(bu 2
\fB\fCportc\fR cleans the files used to build ports.
.IP \(bu 2
\fB\fCporti\fR installs a port.
.IP \(bu 2
\fB\fCports\fR searches for a port.
.IP \(bu 2
\fB\fCportu\fR upgrades a port.
.IP \(bu 2
\fB\fCportU\fR upgrades MacPorts, the ports collection, and outdated ports.
.IP \(bu 2
\fB\fCportx\fR uninstalls a port.
.IP \(bu 2
\fB\fCportX\fR uninstalls inactive ports.
.RE
.SH Authors
.PP
\fIThe authors of this module should be contacted via the issue tracker
.UR https://github.com/sorin-ionescu/prezto/issues
.UE .\fP
.RS
.IP \(bu 2
Matt Cable
.UR https://github.com/curiousstranger
.UE
.IP \(bu 2
Sorin Ionescu
.UR https://github.com/sorin-ionescu
.UE
.RE
