.TH Z
.PP
Integrates z
.UR https://github.com/rupa/z
.UE
into Prezto, which maintains a frequently used directory
list for fast directory changes.
.SH Aliases
.RS
.IP \(bu 2
\fB\fCj\fR changes the current working directory to the most \fIfrecent\fP match.
.RE
.SH Authors
.PP
\fIThe authors of this module should be contacted via the issue tracker
.UR https://github.com/sorin-ionescu/prezto/issues
.UE .\fP
.RS
.IP \(bu 2
Sorin Ionescu
.UR https://github.com/sorin-ionescu
.UE
.RE
