.TH GPG\-Agent
.PP
Provides for an easier use of gpg\-agent
.UR http://linux.die.net/man/1/gpg-agent
.UE .
.SH Authors
.PP
\fIThe authors of this module should be contacted via the issue tracker
.UR https://github.com/sorin-ionescu/prezto/issues
.UE .\fP
.RS
.IP \(bu 2
Florian Walch
.UR https://github.com/fwalch
.UE
.IP \(bu 2
Sorin Ionescu
.UR https://github.com/sorin-ionescu
.UE
.RE
