.TH Completion
.PP
Loads and configures tab completion and provides additional completions from
the zsh\-completions
.UR https://github.com/zsh-users/zsh-completions
.UE
project.
.PP
This module must be loaded \fBafter\fP the \fIutility\fP module.
.SH Contributors
.PP
Completions should be submitted to the zsh\-completions
.UR https://github.com/zsh-users/zsh-completions
.UE
project according
to its rules and regulations. This module will be synchronized against it.
.SH Authors
.PP
\fIThe authors of this module should be contacted via the issue tracker
.UR https://github.com/sorin-ionescu/prezto/issues
.UE .\fP
.RS
.IP \(bu 2
Sorin Ionescu
.UR https://github.com/sorin-ionescu
.UE
.RE
