.TH Node.js
.PP
Provides utility functions for Node.js
.UR http://nodejs.org
.UE
and loads npm
.UR http://npmjs.org
.UE
completion.
.SH Functions
.RS
.IP \(bu 2
\fB\fCnode-doc\fR opens the Node.js online API documentation
.UR http://nodejs.org/api
.UE
in the default
browser.
.RE
.SH Authors
.PP
\fIThe authors of this module should be contacted via the issue tracker
.UR https://github.com/sorin-ionescu/prezto/issues
.UE .\fP
.RS
.IP \(bu 2
Sorin Ionescu
.UR https://github.com/sorin-ionescu
.UE
.RE
