# git
alias gstas='git status'
alias gdif='git diff'
alias glog='git log'
alias gshow='git show '
alias gadd='git add '
alias gcomi='git commit '
alias gcomm='git commit -m '
alias gbrah='git branch '
alias gcheo='git checkout '
alias gpull='git pull '